name: Publish to Exchange & Deploy to CH2.0

on:
  # 1. Mantiene el automático al mergear a main
  push:
    branches: [ main ]
  
  # 2. HABILITA LA EJECUCIÓN MANUAL DESDE CUALQUIER BRANCH
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Ambiente de destino'
        required: true
        default: 'Development'
        type: choice
        options:
          - Development
    
jobs:         
  build:
    runs-on: ubuntu-latest
    permissions: # AÑADIDO: Permite escribir tags
      contents: write
    environment: 
          name: ${{ github.event.inputs.target_env || 'Production' }}
          
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8
      
      - name: Publish to Exchange
        continue-on-error: true
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0        
        env:
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: |
          # Lógica para determinar el ambiente y el nombre de la app
          ENV_NAME=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.target_env || 'Production' }}
          APP_SUFFIX=$([[ "$ENV_NAME" == "Production" ]] && echo "" || echo "-dev")
          echo "DEBUG: Ambiente destino  = [$ENV_NAME]"
          echo "DEBUG: Sufijo generado   = [$APP_SUFFIX]"
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Denv="$ENV_NAME" \
          -Denv.key="${{ secrets.MULE_KEY }}" \
          -Dapp.name="test-pipeline-lfsv$APP_SUFFIX"

      - name: Create Git Tag
        # CONDICIÓN: Éxito Y (es rama main O seleccionaste Production manualmente)
        if: ${{ success() && (github.ref == 'refs/heads/main' || github.event.inputs.target_env == 'Production') }}
        run: |
          # 1. Extraer la versión actual del POM
          APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          echo "Creando tag oficial para la versión: v$APP_VERSION"
          
          # 2. Configurar Git (identidad del bot)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 3. Crear el tag y subirlo
          # Usamos -f (force) por si necesitas re-subir la misma versión después de un error
          git tag -a v$APP_VERSION -m "Release oficial de Producción v$APP_VERSION"
          git push origin v$APP_VERSION